// UI contract test for docs/API-NEXT.md section 3 (web/ui.js + index.html + ui.css). No game server, no AirPod.
// Part A: test/ui-mock.html (the real markup + the real ui.js, nothing else) and every function of section 3 through window.__ui, at 1280x720 and 600x900.
// Part B: the real page with whatever web/main.js is on disk, against a fake lobby: it must boot, walk title -> lobby, ask for a name, and send the old messages.
// Usage: node test/ui-next.mjs      UI_NEXT_PORT=<base> moves the ports (default 8760: pages, 8761: fake lobby, 8762: nothing = no AirPod). ONLY=a | b runs one part.
import http from 'http'; import fs from 'fs'; import path from 'path';
import { WebSocketServer } from 'ws';
import puppeteer from 'puppeteer-core';
const P0 = +process.env.UI_NEXT_PORT || 8760, W = P0, G = P0 + 1, DEAD = P0 + 2, ONLY = (process.env.ONLY || 'ab').toLowerCase(), root = new URL('..', import.meta.url).pathname, sleep = ms => new Promise(r => setTimeout(r, ms));
if ([8080, 8787, 3000].some(p => p >= P0 && p <= P0 + 2)) { console.log('refusing: that port range holds the player\'s own game'); process.exit(2); }
const MIME = { '.html': 'text/html', '.js': 'text/javascript', '.mjs': 'text/javascript', '.css': 'text/css', '.woff2': 'font/woff2', '.json': 'application/json', '.wasm': 'application/wasm', '.png': 'image/png', '.svg': 'image/svg+xml' };
const web = http.createServer((q, r) => { let f = path.join(root, decodeURIComponent(q.url.split('?')[0])); if (!f.startsWith(root)) { r.writeHead(403); return r.end(); } if (f.endsWith('/')) f += 'index.html';
  fs.readFile(f, (e, d) => { r.writeHead(e ? 404 : 200, { 'content-type': MIME[path.extname(f)] || 'application/octet-stream' }); r.end(e ? '' : d); }); }).listen(W, '127.0.0.1');
const CHROME = process.env.CHROME || ['/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', '/usr/bin/google-chrome', '/usr/bin/chromium'].find(p => fs.existsSync(p));
const browser = await puppeteer.launch({ executablePath: CHROME, headless: 'new', args: ['--use-gl=angle', '--enable-unsafe-swiftshader', '--autoplay-policy=no-user-gesture-required', '--use-fake-device-for-media-stream', '--use-fake-ui-for-media-stream', '--hide-scrollbars'] });
const out = [], errs = [], ok = (c, what) => { out.push((c ? 'PASS ' : 'FAIL ') + what); if (!c) console.log('FAIL', what); };
setTimeout(() => { console.log(out.join('\n')); console.log('UI-NEXT FAIL (timeout)'); process.exit(2); }, 300000);
const J = o => JSON.stringify(o), EVIL = '<img src=x onerror="window.__xss=1">';
function watchPage(pg, tag) { pg.on('pageerror', e => errs.push(`[${tag}] PAGEERROR ${e.message}`)); pg.on('response', r => { if (r.status() >= 400) errs.push(`[${tag}] ${r.status()} ${r.url()}`); });
  pg.on('console', m => { if (m.type() === 'error' && !/ERR_CONNECTION_REFUSED|WebSocket connection|Failed to load resource/.test(m.text())) errs.push(`[${tag}] ${m.text()}`); }); }
async function mock(tag, screen, w, h, extra = '') { const pg = await browser.newPage(); await pg.setViewport({ width: w, height: h, deviceScaleFactor: 1 }); watchPage(pg, tag);
  await pg.goto(`http://127.0.0.1:${W}/test/ui-mock.html?screen=${screen}${extra}`); await pg.waitForFunction(() => document.title.startsWith('ready')); await pg.evaluate(() => document.fonts.ready); await sleep(450);
  await pg.evaluate(() => { window.__calls = []; const rec = (k) => (...a) => window.__calls.push([k, ...a]); const ui = window.__ui;
    ui.onSettings({ open: rec('open'), close: rec('close'), sens: rec('sens'), airpod: rec('airpod'), stats: rec('stats'), recenter: rec('recenter'), leave: rec('leave'), name: rec('name'), sound: rec('sound'), sink: rec('sink') });
    ui.onLobby({ quick: rec('quick'), create: rec('create'), join: rec('join'), watch: rec('watch'), bot: rec('bot'), start: rec('start'), back: rec('back'), copied: rec('copied') });
    ui.onView(rec('view')); ui.onRematch(rec('vote'));
    // helpers the checks share. seen = in the render tree and not faded out. hit = do two boxes touch
    window.J = o => JSON.stringify(o);
    window.T = { $: id => document.getElementById(id), seen: id => { const e = document.getElementById(id); if (!e) return false; const c = getComputedStyle(e), r = e.getBoundingClientRect(); return r.width > 0 && c.visibility !== 'hidden' && c.display !== 'none' && +c.opacity > 0.05; },
      box: id => { const r = document.getElementById(id).getBoundingClientRect(); return { l: r.left, t: r.top, r: r.right, b: r.bottom, w: r.width, h: r.height }; },
      hit: (a, b) => { const A = T.box(a), B = T.box(b); return A.w > 0 && B.w > 0 && A.l < B.r - .5 && B.l < A.r - .5 && A.t < B.b - .5 && B.t < A.b - .5; },
      inside: id => { const r = T.box(id); return r.l >= -.5 && r.t >= -.5 && r.r <= innerWidth + .5 && r.b <= innerHeight + .5; }, calls: k => window.__calls.filter(c => c[0] === k), clear: () => { window.__calls.length = 0; } }; });
  return pg; }
const ev = (pg, fn, ...a) => pg.evaluate(fn, ...a);

if (ONLY.includes('a')) for (const [w, h] of [[1280, 720], [600, 900]]) {
  const tag = `${w}x${h}`; let r;
  // ---------- 3.0 exports and ids ----------
  let pg = await mock(tag, 'hud', w, h);
  r = await ev(pg, () => { const want = 'SHOTS shotName showScreen showOverlay currentScreen currentOverlay setNames setScore setServe setRally callout toast toastOff confetti setStatus setLink setServerAddress calibrationReset calibration setMode toggle setCamera isVisible setStat fullscreen wake onStart onRetry cleanCode onLobby lobbyView lobbyRooms lobbyBusy lobbyLink codeError setRoom titleRoom pointBanner matchResult show playerName askWatch asking onSettings settings setSettings setPaused setSpectator setWatchers onView setView onRematch rematch hold viewParent courtsState askCard askShowing onAnswer askPlay askCan showAsk onAsk'.split(' ');
    return want.filter(k => k === 'SHOTS' ? typeof __ui[k] !== 'object' : typeof __ui[k] !== 'function'); });
  ok(!r.length, `${tag} every export of section 3 is there (missing: ${r})`);
  r = await ev(pg, () => { const ids = 'hud board name-me sub-me name-them sub-them sc-me sc-them sv-me sv-them rally banner banner-text callout dev m g pw px py pkmax sw pkavg pklist ping netq nethz keys mode camwrap camv podwrap toast glass room-pill room-code btn-start btn-quick btn-courts btn-create court-search court-seg btn-watch-code btn-tour room-list room-empty result result-title tally-me tally-them tally-sc-me tally-sc-them tally-name-me tally-name-them screen-title screen-lobby screen-connect screen-match screen-server-down screen-game-full row-airpod row-game row-camera row-airpod-text row-airpod-state row-game-text row-game-state row-camera-text row-camera-state downurl down-lan down-net btn-retry corner btn-menu watchers watch-n paused-tag settings set-title set-sens btn-sens-less set-sens-val btn-sens-more tog-airpod btn-recenter tog-full btn-leave-room set-airpod set-game set-camera set-airpod-state set-game-state set-camera-state set-note set-name-input name-row name-input btn-bot lobby-bot btn-bot-0 btn-bot-1 btn-bot-2 btn-bot-3 ask-card btn-ask ask-watch btn-watch-yes btn-watch-no views split-line result-note rematch btn-rematch btn-leave rematch-note rematch-bar rematch-left hold hold-left'.split(' ');
    return { missing: ids.filter(i => !document.getElementById(i)), gone: ['lights', 'st-airpod', 'st-game', 'st-camera', 'key-leave', 'btn-code'].filter(i => document.getElementById(i)), nextUp: document.querySelectorAll('.next-up').length }; });
  ok(!r.missing.length, `${tag} every id of the contract exists (missing: ${r.missing})`); ok(!r.gone.length && !r.nextUp, `${tag} #lights, #st-*, #key-leave and .next-up are gone (left: ${r.gone}, next-up ${r.nextUp})`);

  // ---------- 3.1 corner, key hints, status ----------
  r = await ev(pg, () => { const k = T.$('keys'), c = getComputedStyle(k), cap = getComputedStyle(k.querySelector('.keycap')), b = T.box('keys'), m = T.$('btn-menu');
    const items = () => [...k.querySelectorAll('li')].filter(l => !l.hidden).map(l => l.textContent.trim()); __ui.setBot(null); const plain = items(); __ui.setBot('Pro'); const matt = items(), rowOn = T.seen('set-bot') || !T.$('set-bot').hidden; __ui.setBot(null);
    return { items: plain, matt, rowOn, rowOff: T.$('set-bot').hidden && T.$('key-bot').hidden, bg: c.backgroundColor, border: c.borderTopWidth, shadowBox: c.boxShadow, color: c.color, tshadow: c.textShadow !== 'none', cap: cap.backgroundColor, right: innerWidth - b.r, bottom: innerHeight - b.b, left: b.l,
      menu: { label: m.getAttribute('aria-label'), exp: m.getAttribute('aria-expanded'), left: T.box('btn-menu').l, top: T.box('btn-menu').t, gloss: getComputedStyle(m, '::before').clipPath }, pillAfterMenu: m.nextElementSibling.id, pill: T.seen('room-pill') && T.$('room-code').textContent,
      hits: [['corner', 'board'], ['btn-menu', 'board'], ['room-pill', 'board'], ['keys', 'board'], ['keys', 'podwrap'], ['keys', 'camwrap'], ['corner', 'camwrap']].filter(p => T.hit(...p)).map(p => p.join('x')), tags: ['watchers', 'paused-tag', 'views', 'split-line', 'hold', 'settings'].filter(T.seen) }; });
  ok(r.items.join('|') === 'CCalibrate' && r.matt.join('|') === 'CCalibrate|1234Difficulty: Pro' && r.rowOn && r.rowOff, `${tag} key hints: [C] Calibrate, and against Matt only (setBot) [1][2][3][4] Difficulty: Pro (${r.items.join(' | ')} / ${r.matt.join(' | ')}); docs/NEXT.md 14d`);
  ok(r.bg === 'rgba(0, 0, 0, 0)' && r.border === '0px' && r.shadowBox === 'none' && r.color === 'rgb(255, 255, 255)' && r.tshadow && r.cap === 'rgb(255, 255, 255)', `${tag} key hints: no plate, white words with a shadow, white keycaps (bg ${r.bg}, cap ${r.cap})`);
  ok(r.right < 30 && r.bottom < 30 && r.left > w / 2, `${tag} key hints sit bottom-right (${Math.round(r.right)} px from the right, ${Math.round(r.bottom)} from the bottom)`);
  ok(r.menu.label === 'Settings' && r.menu.exp === 'false' && r.menu.left < 30 && r.menu.top < 30 && /inset/.test(r.menu.gloss) && ['ping-pill', 'room-pill'].includes(r.pillAfterMenu) && r.pill === 'K24M', `${tag} hamburger top-left, named Settings, keeps the .btn gloss clip (${r.menu.gloss.slice(0, 24)}), room code beside it (${r.pill})`);
  ok(!r.hits.length && !r.tags.length, `${tag} player HUD: nothing overlaps (${r.hits}), no spectator or pause bits showing (${r.tags})`);
  r = await ev(pg, () => { __ui.setStatus({ airpod: 'bad', game: 'wait', camera: 'off', nonsense: 'ok', game2: 'bad' }); const s = k => [T.$('set-' + k).className, T.$(`set-${k}-state`).textContent, T.$('row-' + k).className.replace('status-row ', ''), T.$(`row-${k}-state`).textContent].join('/');
    const a = [s('airpod'), s('game'), s('camera')]; __ui.setStatus({ airpod: 'ok', game: 'ok', camera: 'ok' }); return { a, show: [__ui.show('dev', true), T.seen('dev'), __ui.show('dev', false), T.seen('dev'), __ui.show('no-such-id', true), __ui.toggle('no-such-id'), __ui.isVisible('no-such-id')] }; });
  ok(r.a.join(' ') === 'is-bad/Problem/is-bad/Problem is-wait/Waiting/is-wait/Waiting is-off/Off/is-off/Off', `${tag} setStatus writes the settings rows and the connect rows (${r.a.join(' ')})`);
  ok(J(r.show) === J([true, true, false, false, false, false, false]), `${tag} show(id, on) returns what is shown, and is null-safe (${J(r.show)})`);

  // ---------- 3.2 settings ----------
  await pg.click('#btn-menu'); await sleep(350);
  await ev(pg, () => __ui.setSettings({ sinkWhy: 'browser' }));      // pin the Sound group: whether THIS browser can move audio is not what the row list is about
  r = await ev(pg, () => ({ open: __ui.settings(), body: document.body.dataset.settings, exp: T.$('btn-menu').getAttribute('aria-expanded'), calls: __calls.map(c => c[0]), focusIn: T.$('settings').contains(document.activeElement), focusTag: document.activeElement.tagName, title: T.$('set-title').textContent, inside: T.inside('settings'),
    hits: ['board', 'room-pill', 'btn-menu', 'keys'].filter(i => T.hit('settings', i)), glass: getComputedStyle(T.$('glass')).visibility, top: (() => { const b = T.box('settings'), e = document.elementFromPoint(b.l + b.w / 2, b.t + 20); return !!e && !!e.closest('#settings'); })(),
    alpha: getComputedStyle(T.$('settings')).backgroundImage, rows: [...document.querySelectorAll('#settings .set-row > span:first-child, #settings > .btn, #settings .set-status b')].filter(e => e.offsetParent).map(e => e.textContent).join('|'), current: __ui.currentScreen() + '/' + __ui.currentOverlay() }));
  ok(r.open === true && r.body === 'open' && r.exp === 'true' && J(r.calls) === J(['open']) && r.focusIn && r.focusTag !== 'INPUT', `${tag} hamburger opens the panel: open() once, aria-expanded, focus in the card and not in its name field (${J(r.calls)}, focus ${r.focusTag})`);
  ok(r.rows === 'AirPod|Game|Camera|Name|Sensitivity|Show AirPod|Recentre camera|Move|Sound|Full screen|Leave court' && r.title === 'Settings', `${tag} settings rows: ${r.rows}`);
  ok(r.inside && !r.hits.length && r.top && r.glass === 'hidden' && /rgba/.test(r.alpha) && r.current === 'null/null', `${tag} live: the card is see-through, no blur, covers neither the scoreboard nor the room code (${r.hits}), and is no screen (${r.current})`);
  // Sound (NOTES 60): the Output row is there only where the browser can actually move the audio, otherwise a hint saying where to go. Its own `snd`: `r` is still read below
  const DEVS = [{ id: '', label: 'System default' }, { id: 'spk', label: 'MacBook Pro Speakers' }, { id: 'pods', label: 'Daniel’s AirPods' }];
  const snd = await ev(pg, devs => { const sel = () => T.$('set-sink-sel'), state = o => { __ui.setSettings(o); return [T.seen('set-sink'), T.seen('sink-hint'), T.$('sink-hint').textContent.slice(0, 22), [...sel().options].map(x => x.textContent).join('/'), sel().value]; };
    const out = { browser: state({ sinkWhy: 'browser', sinks: devs }), nogrant: state({ sinkWhy: 'devices', sinks: [devs[0]] }), denied: state({ sinkWhy: 'denied', sinks: [devs[0]] }), listed: state({ sinkWhy: '', sinks: devs, sink: 'pods' }) };
    // "Find my speakers" is offered ONLY where asking can still help: not in a browser that cannot switch, not after a refusal, not once they are listed
    out.askBtn = ['browser', 'devices', 'denied', ''].map(w => { __ui.setSettings({ sinkWhy: w, sinks: w === '' ? devs : [devs[0]] }); return T.seen('btn-find-sinks'); });
    // the row must report the player's pick, not flip itself: ui.js only ever hands the value to main.js
    T.clear(); sel().value = 'spk'; sel().dispatchEvent(new Event('change', { bubbles: true })); out.chose = T.calls('sink').map(c => c[1]); out.stillPods = sel().value;
    out.evil = (() => { __ui.setSettings({ sinkWhy: '', sinks: [{ id: 'x', label: '<img src=x onerror="window.__xss=1">' }] }); return [sel().querySelectorAll('img').length, !window.__xss, sel().options[0].textContent.slice(0, 9)]; })();
    __ui.setSettings({ sinkWhy: 'browser' }); return out; }, DEVS);
  ok(J(snd.browser.slice(0, 3)) === J([false, true, 'This browser can’t mov']) && J(snd.nogrant.slice(0, 3)) === J([false, true, 'Your browser only name']) && J(snd.denied.slice(0, 3)) === J([false, true, 'Audio permission is bl']),
     `${tag} Sound: no Output row without setSinkId, without named devices, or after a refusal, and the hint says which (${J(snd.browser.slice(0, 3))} / ${J(snd.nogrant.slice(0, 3))} / ${J(snd.denied.slice(0, 3))})`);
  ok(J(snd.askBtn) === J([false, true, false, false]), `${tag} Sound: "Find my speakers" only where asking can still help (browser/devices/denied/listed = ${J(snd.askBtn)})`);
  ok(snd.listed[0] === true && !snd.listed[1] && snd.listed[3] === 'System default/MacBook Pro Speakers/Daniel’s AirPods' && snd.listed[4] === 'pods',
     `${tag} Sound: the Output row lists every named device and shows the chosen one (${snd.listed[3]} = ${snd.listed[4]})`);
  ok(J(snd.chose) === J(['spk']) && snd.stillPods === 'spk', `${tag} Sound: choosing an output hands the deviceId to main.js (${J(snd.chose)})`);
  ok(snd.evil[0] === 0 && snd.evil[1] === true && snd.evil[2] === '<img src=', `${tag} a hostile device name is text, never markup (${J(snd.evil)})`);
  await pg.click('#btn-sens-more'); await pg.click('#btn-sens-less'); await pg.click('#tog-airpod'); await pg.click('#btn-recenter'); await pg.click('#btn-leave-room');
  r = await ev(pg, () => ({ calls: __calls.slice(1), air: T.$('tog-airpod').getAttribute('aria-checked') }));
  ok(J(r.calls) === J([['sens', 1], ['sens', -1], ['airpod', false], ['recenter'], ['leave']]) && r.air === 'true', `${tag} rows call main.js with the NEW value and flip nothing themselves (${J(r.calls)})`);
  r = await ev(pg, () => { __ui.setSettings({ sens: 14, sensMax: true, sensMin: false, airpod: false, stats: true, inRoom: false, canPause: false }); const a = { val: T.$('set-sens-val').textContent, more: T.$('btn-sens-more').disabled, less: T.$('btn-sens-less').disabled, air: T.$('tog-airpod').getAttribute('aria-checked'), leave: T.seen('btn-leave-room'), note: T.seen('set-note') && T.$('set-note').textContent };
    __ui.setSettings({ spectator: true }); a.spec = ['set-name', 'set-sens', 'tog-airpod', 'btn-recenter', 'set-airpod', 'set-camera', 'tog-full', 'set-game'].filter(T.seen); __ui.setSettings({ spectator: false, inRoom: true, canPause: true, sensMax: false }); __ui.setSettings(); __ui.setSettings({ junk: 1 }); a.note2 = T.seen('set-note'); return a; });
  ok(r.val === '14' && r.more && !r.less && r.air === 'false' && !r.leave && r.note === 'Online games can’t pause' && !r.note2, `${tag} setSettings draws what it is given (sens ${r.val}, + disabled ${r.more}, note "${r.note}")`);
  ok(r.spec.join() === 'tog-full,set-game', `${tag} spectator settings keep only Full screen and Game (${r.spec})`);
  // name row (NEXT 10b)
  await pg.click('#set-name-input', { clickCount: 3 }); await pg.keyboard.type(' Ann<>  Lee '); await pg.keyboard.press('Enter'); await sleep(80);
  r = await ev(pg, () => ({ calls: T.calls('name'), lobby: T.$('name-input').value, stored: localStorage.getItem('poddle.name'), name: __ui.playerName(), open: __ui.settings(), focus: document.activeElement.id }));
  ok(J(r.calls) === J([['name', 'Ann Lee']]) && r.lobby === 'Ann Lee' && r.stored === 'Ann Lee' && r.name === 'Ann Lee' && r.open && r.focus === 'settings', `${tag} settings Name row: cleaned, saved, handed to main.js, shared with the lobby field (${J(r.calls)})`);
  await pg.click('#set-name-input', { clickCount: 3 }); await pg.keyboard.press('Backspace'); await pg.keyboard.press('Tab'); r = await ev(pg, () => [T.$('set-name-input').value, T.calls('name').length]); ok(r[0] === 'Ann Lee' && r[1] === 1, `${tag} an emptied Name row puts the old name back (${r[0]})`);
  // keyboard: Tab / arrows reach every control, focus is visible
  r = await ev(pg, async () => { const s = T.$('settings'); s.focus(); const seen = []; for (let i = 0; i < 9; i++) { s.dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowDown', bubbles: true })); document.activeElement.dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowDown', bubbles: true })); } return null; });
  await ev(pg, () => T.$('settings').focus()); const walked = []; for (let i = 0; i < 10; i++) { await pg.keyboard.press('Tab'); walked.push(await ev(pg, () => document.activeElement.id)); }
  ok(walked.join() === 'set-name-input,btn-sens-less,btn-sens-more,tog-airpod,btn-recenter,,,tog-sound,tog-full,btn-leave-room',      // (the two Move choices, Body and Auto, have no id)
     `${tag} Tab reaches every control in order (${walked})`);
  r = await ev(pg, () => { const b = T.$('tog-full'); b.focus(); return getComputedStyle(b).boxShadow !== 'none' || getComputedStyle(b).borderColor; }); ok(!!r, `${tag} a focused row shows it`);
  // outside click closes, once; settings(true/false) fire once per real change
  await ev(pg, () => T.clear()); await pg.mouse.click(w - 40, h / 2); await sleep(120);
  r = await ev(pg, () => { const a = { open: __ui.settings(), calls: __calls.map(c => c[0]), focus: document.activeElement.id, body: document.body.dataset.settings }; T.clear(); __ui.settings(true); __ui.settings(true); __ui.settings(false); __ui.settings(false); a.api = __calls.map(c => c[0]); return a; });
  ok(r.open === false && J(r.calls) === J(['close']) && r.body === undefined, `${tag} a click outside closes it, close() once (${J(r.calls)})`); ok(J(r.api) === J(['open', 'close']), `${tag} settings(true) twice and settings(false) twice fire one open and one close (${J(r.api)})`);
  r = await ev(pg, async () => { T.clear(); __ui.settings(true); __ui.showScreen('lobby'); const a = [__ui.settings(), __calls.map(c => c[0]).join()]; __ui.showScreen(null); T.clear(); __ui.settings(true); __ui.matchResult({ won: true, me: 11, them: 3, nameThem: 'Bo' }); a.push(__ui.settings(), __calls.map(c => c[0]).join()); const under = __ui.settings(true); __ui.showOverlay(null); return [...a, under]; });
  ok(J(r) === J([false, 'open,close', false, 'open,close', false]), `${tag} a menu screen and the result close the panel and say so; it does not open under them (${J(r)})`);
  // paused
  r = await ev(pg, async () => { __ui.setPaused(true); const a = { tagClosed: T.seen('paused-tag'), tagText: T.$('paused-tag').textContent }; __ui.settings(true); await new Promise(r => setTimeout(r, 450)); const g = getComputedStyle(T.$('glass'));
    Object.assign(a, { title: T.$('set-title').textContent, glass: g.visibility + '/' + g.opacity, blur: g.backdropFilter || g.webkitBackdropFilter, tagOpen: T.seen('paused-tag'), body: document.body.dataset.paused, menuOnTop: (() => { const b = T.box('btn-menu'), e = document.elementFromPoint(b.l + b.w / 2, b.t + b.h / 2); return !!e && !!e.closest('#btn-menu'); })(), z: [getComputedStyle(T.$('settings')).zIndex, g.zIndex] }); return a; });
  ok(r.title === 'Paused' && r.glass === 'visible/1' && /blur\(/.test(r.blur) && r.menuOnTop && r.body === '1', `${tag} paused + open: title "${r.title}", the blur layer is up behind the card (${r.glass}, ${r.blur}), the hamburger stays on top`);
  ok(r.tagClosed && r.tagText === 'Paused' && !r.tagOpen, `${tag} paused + closed shows the "Paused" tag, open does not (${r.tagClosed}/${r.tagOpen})`);
  await pg.screenshot({ path: `${root}test/ui-shots/next-settings-paused-${tag}.png` });
  r = await ev(pg, async () => { __ui.setPaused(false); await new Promise(r => setTimeout(r, 450)); const a = [T.$('set-title').textContent, getComputedStyle(T.$('glass')).visibility, T.seen('paused-tag'), document.body.dataset.paused]; __ui.settings(false); return a; });
  ok(J(r) === J(['Settings', 'hidden', false, null]) || J(r) === J(['Settings', 'hidden', false, undefined]), `${tag} setPaused(false) puts it all back (${J(r)})`);
  await pg.close();

  // ---------- 3.3 lobby ----------
  pg = await mock(tag, 'lobby-first', w, h); await sleep(800);      // the tiles deal themselves in (ui.css .tile, 560 ms + 140 ms stagger): measure them settled
  r = await ev(pg, () => ({ focus: document.activeElement.id, value: T.$('name-input').value, max: T.$('name-input').maxLength, ac: T.$('name-input').autocomplete, spell: T.$('name-input').spellcheck, label: document.querySelector('#name-row label').textContent, dim: getComputedStyle(T.$('btn-quick')).opacity, aria: T.$('btn-quick').getAttribute('aria-disabled'),
    tiles: [...document.querySelectorAll('#lobby-home .tile')].map(b => b.querySelector('b').textContent.trim()), tops: [...document.querySelectorAll('#lobby-home .tile')].map(b => Math.round(b.getBoundingClientRect().top)), lefts: [...document.querySelectorAll('#lobby-home .tile')].map(b => Math.round(b.getBoundingClientRect().left)),
    inside: ['name-row', 'lobby-home'].every(T.inside) && [...document.querySelectorAll('#lobby-home .tile')].every(e => { const b = e.getBoundingClientRect(); return b.left >= 0 && b.right <= innerWidth && b.top >= 0 && b.bottom <= innerHeight; }), sub: T.$('courts-n').textContent, list: !!document.querySelector('#lobby-home .rooms, #lobby-home #room-list') }));
  ok(r.focus === 'name-input' && r.value === '' && r.max === 12 && r.ac === 'off' && r.spell === false && r.label === 'Name', `${tag} first visit: the empty name field has focus (${r.focus}), maxlength ${r.max}, label "${r.label}"`);
  ok(r.tiles.join('|') === 'Quick play|Courts|Play a bot' && !r.list && r.sub === '8 open', `${tag} three tiles: ${r.tiles.join(' | ')}, no list on home, the Courts tile says "${r.sub}"`);
  ok(new Set(r.tops).size === 1, `${tag} tiles are three across (tops ${r.tops}) and everything fits: ${r.inside}`); ok(r.inside, `${tag} lobby fits the window`);
  ok(+r.dim < 0.7 && r.aria === 'true', `${tag} no name yet: the choices are dimmed and aria-disabled (opacity ${r.dim})`);
  await pg.screenshot({ path: `${root}test/ui-shots/next-lobby-first-${tag}.png` });
  for (const sel of ['#btn-quick', '#btn-courts', '#btn-bot', 'courts', '#btn-create', '.room-row[data-code="KXQ7"]', '.room-watch[data-watch="KXQ7"]']) { if (sel === 'courts') { await ev(pg, () => __ui.lobbyView('courts')); await sleep(150); continue; } await ev(pg, () => document.activeElement.blur()); await pg.click(sel); await sleep(60);
    r = await ev(pg, () => ({ calls: __calls.length, view: __ui.lobbyView(), focus: document.activeElement.id, err: T.$('name-row').classList.contains('is-error') })); ok(r.calls === 0 && (r.view === 'home' || r.view === 'courts' && !sel.includes('btn-quick')) && r.focus === 'name-input' && r.err, `${tag} no name: ${sel} fires nothing, the field shakes and takes focus (${r.view})`); }
  await ev(pg, () => __ui.lobbyView('home')); await sleep(120);
  await pg.keyboard.type('  Dan\tiel<>   Tan the Third  '); r = await ev(pg, () => ({ name: __ui.playerName(), stored: localStorage.getItem('poddle.name'), dim: getComputedStyle(T.$('btn-quick')).opacity, set: T.$('set-name-input').value })); ok(r.name === 'Daniel Tan' || r.name === 'Dan iel Tan' || r.name.length <= 12, `${tag} playerName() is clean and at most 12 long: "${r.name}" (stored "${r.stored}")`);
  r = await ev(pg, () => { const i = T.$('name-input'); i.value = ' \u0007<Da\u0000n>   iel   the  very long one'; i.dispatchEvent(new Event('input', { bubbles: true })); const now = [__ui.playerName(), localStorage.getItem('poddle.name')]; return new Promise(res => setTimeout(() => res([...now, getComputedStyle(T.$('btn-quick')).opacity, T.$('btn-quick').getAttribute('aria-disabled')]), 800)); });      // name and store read at once (saved on every change); the un-dim fades in (ui.css .tile opacity transition), so its opacity is read settled
  ok(r[0] === 'Dan iel the' && r[1] === 'Dan iel the' && +r[2] === 1 && r[3] === null, `${tag} control characters and < > go, spaces collapse, first 12, saved on every change: "${r[0]}"`);
  await pg.focus('#name-input'); await pg.keyboard.press('Enter'); await sleep(60); ok(await ev(pg, () => document.activeElement.id) === 'btn-quick', `${tag} Enter in the name field moves to Quick play`);
  for (const k of ['ArrowRight', 'ArrowRight']) await pg.keyboard.press(k); ok(await ev(pg, () => document.activeElement.id) === 'btn-bot', `${tag} arrows walk to the third tile`);
  await pg.keyboard.press('Enter'); await sleep(300); r = await ev(pg, () => ({ view: __ui.lobbyView(), title: T.$('lobby-title').textContent, focus: document.activeElement.id, head: T.$('bot-title').textContent, btns: [...document.querySelectorAll('#lobby-bot [data-level]')].map(b => b.textContent + b.dataset.level + (b.classList.contains('btn') ? '' : '!')).join(), name: T.seen('name-row'), fit: T.inside('lobby-bot') }));
  ok(r.view === 'bot' && r.title === 'Play a bot' && r.focus === 'btn-bot-1' && r.btns === 'RookieSlow and forgiving0,ClubA fair match1,TourTournament pace3,ProFast and accurate2' && r.head === 'Select difficulty' && r.name && r.fit, `${tag} Play a bot view: "${r.title}", ${r.btns}, Club focused (${r.focus})`);
  await pg.screenshot({ path: `${root}test/ui-shots/next-lobby-bot-${tag}.png` });
  await pg.keyboard.press('ArrowRight'); await pg.keyboard.press('Enter'); await pg.click('#btn-bot-0'); r = await ev(pg, () => J(T.calls('bot'))); ok(r === J([['bot', 3], ['bot', 0]]), `${tag} a level fires bot(level) at once, and Right from Club is Tour: ${r}`);
  // name field vs the code form
  await ev(pg, () => { T.clear(); __ui.lobbyView('code', { code: 'AB' }); }); await sleep(200); r = await ev(pg, () => ({ focusBox: [...document.querySelectorAll('#code-boxes input')].indexOf(document.activeElement), name: T.seen('name-row') })); ok(r.focusBox === 2 && r.name && await ev(pg, () => __ui.lobbyView()) === 'courts', `${tag} lobbyView('code') lands on Courts: prefilled, third box focused, name field still there`);
  await pg.click('#name-input', { clickCount: 3 }); await pg.keyboard.type('Zed'); r = await ev(pg, () => [T.$('name-input').value, [...document.querySelectorAll('#code-boxes input')].map(b => b.value).join('')]); ok(r[0] === 'Zed' && r[1] === 'AB', `${tag} typing a name is not swallowed by the code boxes (name "${r[0]}", code "${r[1]}")`);
  await pg.keyboard.press('Enter'); await pg.keyboard.type('cd'); await pg.keyboard.press('Enter'); await sleep(80); r = await ev(pg, () => J(T.calls('join'))); ok(r === J([['join', 'ABCD']]), `${tag} Enter in the name field goes on to the code, Enter there joins: ${r}`);
  r = await ev(pg, () => { __ui.lobbyView('share'); const a = T.seen('name-row'); __ui.lobbyView('create'); return [a, T.seen('name-row')]; }); ok(!r[0] && r[1], `${tag} the name field hides on the share view only`);
  r = await ev(pg, async () => { __ui.lobbyView('courts', { code: 'M3PD', watch: true }); await new Promise(r => setTimeout(r, 200)); const a = { focus: document.activeElement.id, lit: T.$('btn-watch-code').classList.contains('is-focus'), boxes: [...document.querySelectorAll('#code-boxes input')].map(b => b.value).join('') };
    __ui.lobbyView('courts', { code: 'KXQ7' }); await new Promise(r => setTimeout(r, 200)); a.join = document.activeElement.id; __ui.lobbyView('courts', { code: '' }); return a; });
  ok(r.focus === 'btn-watch-code' && r.lit && r.boxes === 'M3PD' && r.join === 'btn-join', `${tag} a watch link lands on Courts with the boxes filled (${r.boxes}) and Watch focused (${r.focus}); a join link focuses Join (${r.join})`);
  // the court list (docs/COURTS-TOURNEY.md 2.7)
  const LIST5 = [{ code: 'KXQ7', players: 1, open: true, ask: false, watch: 8, watchers: 0, score: [0, 0], live: false, names: ['Dan', null] }, { code: 'M3PD', players: 2, open: false, watch: 6, watchers: 2, score: [7, 4], live: true, names: ['Ann', 'Ben'] },
    { code: 'RN2S', players: 2, open: false, watch: 0, watchers: 8, score: [10, 9], live: true, names: ['Pri', 'Sam'] }, { code: 'WXYZ', players: 1, open: true }, { code: 'KXQ9', players: 1, open: false, ask: true, bot: true, watch: 7, watchers: 1, score: [4, 6], live: true, names: ['Lu', 'Matt'] }];
  const rowsNow = () => [...document.querySelectorAll('#room-list > li')].map(l => { const row = l.firstElementChild, wb = l.querySelector('.room-watch'), q = c => row.querySelector(c)?.textContent;
    return `${l.dataset.kind}:${row.tagName}.${row.classList.contains('room-row') ? 'room-row' : ''}[${row.dataset.code}]${row.hasAttribute('data-nav') ? 'nav' : ''}${row.getAttribute('aria-disabled') === 'true' ? '!' : ''} "${q('.court-who')}|${q('.court-meta')}|${q('.court-go')}"${wb ? ` +${wb.textContent}(${wb.dataset.watch})` : ''}`; });
  r = await ev(pg, (L, rn) => { __ui.lobbyView('courts'); T.clear(); T.$('court-seg').querySelector('[data-filter="open"]').click(); __ui.lobbyRooms(L, 2, [{ code: 'T8MX', host: 'Kai', n: 5, max: 16 }]);
    const f = new Function('return ' + rn)(); const open = f(); T.$('court-seg').querySelector('[data-filter="full"]').click(); return { open, full: f(), n: [T.$('n-open').textContent, T.$('n-full').textContent] }; }, LIST5, rowsNow.toString());
  ok(J(r.open) === J(['tour:BUTTON.room-row[T8MX]nav "TournamentKai’s tournament|5 of 16 joined|Join"', 'open:BUTTON.room-row[KXQ7]nav "Dan is waiting||Join" +Watch(KXQ7)', 'open:BUTTON.room-row[WXYZ]nav "A player is waiting||Join"', 'ask:BUTTON.room-row[KXQ9]nav "Lu vs Matt|4-6|Ask to play" +Watch(KXQ9)'])
    && J(r.full) === J(['full:BUTTON.room-row[RN2S]nav! "Pri vs Sam|10-9 · 8 watching|Stands full"', 'full:BUTTON.room-row[M3PD]nav "Ann vs Ben|7-4 · 2 watching|Watch"']) && r.n.join() === '4,2', `${tag} Open: tournament, someone waiting, ask rows, empty; Full: most watched first, Stands full disabled (${r.n}): ${r.open.join('  ;  ')}  //  ${r.full.join('  ;  ')}`);
  await pg.click('.room-row[data-code="M3PD"]'); await pg.click('.room-row[data-code="RN2S"]'); await ev(pg, () => T.$('court-seg').querySelector('[data-filter="open"]').click()); await sleep(50);
  await pg.click('.room-watch[data-watch="KXQ7"]'); await pg.click('.room-row[data-code="KXQ9"]'); await pg.click('.room-row[data-code="T8MX"]'); r = await ev(pg, () => J(__calls));
  ok(r === J([['watch', 'M3PD'], ['watch', 'KXQ7'], ['join', 'KXQ9'], ['join', 'T8MX']]), `${tag} a Full row watches, Stands full does nothing, Watch -> watch(code), Ask to play and Join -> join(code): ${r}`);
  r = await ev(pg, () => { const i = T.$('court-search'), type = v => { i.value = v; i.dispatchEvent(new Event('input')); }, codes = () => [...document.querySelectorAll('#room-list .court-row')].map(b => b.dataset.code).join();
    type('q9'); const a = { q: i.value, rows: codes(), n: T.$('n-open').textContent + '/' + T.$('n-full').textContent }; type('m3'); a.other = T.$('room-empty').textContent; type('kx'); a.pre = codes(); type('zzzz'); type('HJKM'); a.unlisted = T.$('room-empty').textContent; type(''); return a; });
  ok(r.q === 'Q9' && r.rows === 'KXQ9' && r.n === '1/0' && /No courts match “M3”\..*1 in Full/.test(r.other) && r.pre === 'KXQ7,KXQ9' && /HJKM isn’t listed\. Private courts join by code\.Use this code/.test(r.unlisted), `${tag} search: upper-cased substring, the tab counts follow it, "${r.other}", "${r.unlisted}"`);
  r = await ev(pg, (EVIL) => { const rooms = [{ code: 'KXQ7', players: 1, open: true, watch: 8, watchers: 0, score: [0, 0] }, { code: 'M3PD', players: 2, open: false, watch: 6, watchers: 2, score: [7, 4] }]; T.$('court-seg').querySelector('[data-filter="full"]').click(); __ui.lobbyRooms(rooms, 2); const node = document.querySelector('.room-row[data-code="M3PD"]'); node.focus();
    __ui.lobbyRooms(rooms, 2); const same = node === document.querySelector('.room-row[data-code="M3PD"]'); rooms[1] = { ...rooms[1], score: [8, 4], watchers: 3 }; __ui.lobbyRooms(rooms, 2); const a = { same, text: document.querySelector('.room-row[data-code="M3PD"] .court-meta').textContent, focus: document.activeElement.dataset.code };
    T.$('court-seg').querySelector('[data-filter="open"]').click(); __ui.lobbyRooms([...Array(42)].map((_, i) => ({ code: 'RA' + 'ABCDEFGHJK'[(i / 10) | 0] + 'ABCDEFGHJK'[i % 10], players: 1, open: true })), 2); a.cap = document.querySelectorAll('#room-list > li').length; a.scrolls = T.$('room-list').scrollHeight > T.$('room-list').clientHeight && !T.$('room-bar').hidden;
    { const i = T.$('court-search'); i.value = 'RAEB'; i.dispatchEvent(new Event('input')); a.last = [...document.querySelectorAll('#room-list .court-row')].map(b => b.dataset.code).join(); i.value = ''; i.dispatchEvent(new Event('input')); }      // the 42nd row is found by search (codes from the court alphabet, no 0 or 1: search drops what a code can't hold)
    T.$('court-seg').querySelector('[data-filter="full"]').click(); __ui.lobbyRooms([{ code: EVIL, players: 2, open: false, watch: 3, watchers: '<b>9</b>', score: ['<i>1</i>', {}] }, null, 7, { code: 5 }], 2); a.evil = document.querySelector('#room-list b').textContent === EVIL && !document.querySelector('#room-list img, #room-list i') && document.querySelectorAll('#room-list > li').length === 1; a.evilText = document.querySelector('#room-list .court-meta').textContent;
    T.$('court-seg').querySelector('[data-filter="open"]').click(); __ui.lobbyRooms([{ code: 'KXQ7', players: 1, open: true, watch: 8 }], 2); document.querySelector('.court-row').focus(); __ui.lobbyRooms([], 0); a.empty = T.seen('room-empty') && T.$('room-empty').textContent; a.focusAfter = document.activeElement.id; a.state = __ui.courtsState(); __ui.lobbyRooms(); return a; }, EVIL);
  ok(r.same && r.text === '8-4 · 3 watching' && r.focus === 'M3PD', `${tag} the list only redraws on a change, a new score or watcher count is one, and focus stays on the row (${r.text}, focus ${r.focus})`);
  ok(r.cap === 42 && r.last === 'RAEB' && r.scrolls && r.evil && r.evilText === '0-0' && r.empty === 'No open courts right now.Create court' && r.focusAfter === 'court-search' && r.state === 'empty-open', `${tag} 42 rows rendered and scrollable (no cap: ${r.cap}, scrolls ${r.scrolls}), search finds the 42nd (${r.last}), evil ${r.evil}, state ${r.state}, a hostile list is text or dropped ("${r.evilText}"), empty says "${r.empty}", focus to ${r.focusAfter}`);
  r = await ev(pg, () => { __ui.lobbyView('courts'); T.$('court-seg').querySelector('[data-filter="open"]').click(); const look = () => ({ st: __ui.courtsState(), skel: document.querySelectorAll('#room-list > li.is-skel .court-row.is-skel').length, rows: document.querySelectorAll('#room-list .court-row:not(.is-skel)').length, busy: T.$('room-list').getAttribute('aria-busy'), empty: T.seen('room-empty') ? T.$('room-empty').textContent : '', n: T.$('n-open').textContent + '/' + T.$('n-full').textContent });
    __ui.lobbyLink(false); const down = look(); __ui.lobbyLink(true); const loading = look(); __ui.lobbyRooms([{ code: 'KXQ7', players: 1, open: true, watch: 8 }], 2); const back = look(); return { down, loading, back }; });      // docs/COURTS-TOURNEY.md 2.7: down and loading each show their own state, never a false 0
  ok(r.down.st === 'down' && r.down.skel === 4 && !r.down.rows && /Courts show again when the game is back\./.test(r.down.empty) && r.down.n === '–/–', `${tag} down: 4 skeleton rows, "${r.down.empty}", counts ${r.down.n}`);
  ok(r.loading.st === 'loading' && r.loading.skel === 4 && !r.loading.rows && r.loading.busy === 'true' && r.loading.n === '–/–', `${tag} back up, before the first list: loading, aria-busy ${r.loading.busy}, 4 skeleton rows, counts ${r.loading.n}`);
  ok(r.back.st === 'rows' && r.back.rows === 1 && !r.back.skel && r.back.busy === 'false', `${tag} the first list draws the rows (aria-busy ${r.back.busy})`);
  await ev(pg, () => __ui.lobbyView('home'));
  // watch prompt
  r = await ev(pg, async () => { T.clear(); __ui.askWatch('M3PD'); await new Promise(r => setTimeout(r, 150)); return { asking: __ui.asking(), seen: T.seen('ask-watch'), text: T.$('ask-title').textContent, btns: T.$('btn-watch-yes').textContent + '/' + T.$('btn-watch-no').textContent, focus: document.activeElement.id, inert: T.$('lobby-home').inert, fit: T.inside('ask-watch'), cls: T.$('ask-watch').className }; });
  ok(r.asking && r.seen && r.text === 'Court is full. Watch instead?' && r.btns === 'Yes/No' && r.focus === 'btn-watch-yes' && r.inert && r.fit && /panel/.test(r.cls) && /notice/.test(r.cls), `${tag} watch prompt: "${r.text}" ${r.btns}, Yes focused, the lobby behind it is inert`);
  await pg.screenshot({ path: `${root}test/ui-shots/next-ask-watch-${tag}.png` });
  await pg.keyboard.press('ArrowRight'); r = await ev(pg, () => document.activeElement.id); await pg.keyboard.press('ArrowLeft'); await pg.keyboard.press('Enter'); await sleep(300);      // the prompt shrinks away (200 ms, ui.css .ask.lob-out) before it leaves the render tree
  ok(r === 'btn-watch-no' && await ev(pg, () => J(__calls) + __ui.asking() + T.seen('ask-watch') + T.$('lobby-home').inert) === J([['watch', 'M3PD']]) + 'falsefalsefalse', `${tag} arrows walk Yes / No; Yes fires watch(code) and closes the prompt`);
  r = await ev(pg, async () => { T.clear(); __ui.askWatch('ABCD'); T.$('btn-watch-no').click(); const a = [__ui.asking(), __calls.length]; __ui.askWatch('ABCD'); __ui.askWatch(null); a.push(__ui.asking()); __ui.askWatch('ABCD'); __ui.showScreen('connect'); a.push(__ui.asking()); __ui.showScreen('lobby'); a.push(T.seen('ask-watch')); return a; });
  ok(J(r) === J([false, 0, false, false, false]), `${tag} No, askWatch(null) and leaving the lobby all close it, none fires (${J(r)})`);
  await pg.close();

  // ---------- 3.4 spectator HUD ----------
  pg = await mock(tag, 'watch', w, h);
  r = await ev(pg, () => ({ role: document.body.dataset.role, seen: ['watchers', 'views', 'btn-menu', 'room-pill', 'board'].filter(T.seen), hidden: ['keys', 'podwrap', 'camwrap', 'split-line', 'paused-tag'].filter(T.seen), n: T.$('watch-n').textContent, aria: T.$('watchers').getAttribute('aria-label'), tag: !!T.$('watch-tag'),
    chips: [...document.querySelectorAll('#views .view-chip')].map(c => c.dataset.view + ':' + c.textContent + ':' + c.getAttribute('aria-pressed')).join(' '), left: T.box('views').l, bottom: innerHeight - T.box('views').b, view: document.body.dataset.view, names: T.$('name-me').textContent + '/' + T.$('name-them').textContent,
    hits: [['corner', 'board'], ['watchers', 'board'], ['room-pill', 'board'], ['views', 'board'], ['views', 'corner']].filter(p => T.hit(...p)).map(p => p.join('x')), fit: T.inside('corner') && T.inside('views'), stageHit: (() => { const e = document.elementFromPoint(innerWidth / 2, innerHeight / 2); return e ? (e.id || e.tagName) : ''; })() }));
  ok(r.role === 'spectator' && r.seen.length === 5 && !r.hidden.length && r.tag === false && r.n === '3' && r.aria === '3 watching', `${tag} spectator HUD: no Watching tag (the view chips say it), 3 watching ("${r.aria}"), chips; no key hints, no insets (${r.hidden})`);
  ok(r.chips === 'broadcast:1Broadcast:true split:2Split:false pov:3Player:false free:4Free:false' && r.view === 'broadcast' && r.left < 30 && r.bottom < 30, `${tag} four chips bottom-left: ${r.chips}`);
  ok(!r.hits.length && r.fit && !/^(hud|views|corner|board)$/.test(r.stageHit), `${tag} spectator HUD overlaps nothing (${r.hits}); the middle of the court is free for the orbit drag (hit: ${r.stageHit})`);
  await pg.screenshot({ path: `${root}test/ui-shots/next-watch-${tag}.png` });
  await pg.click('.view-chip[data-view="pov"]'); await pg.click('.view-chip[data-view="split"]');
  r = await ev(pg, (EVIL) => { const a = { calls: J(__calls), pressed: document.querySelector('[aria-pressed="true"]').dataset.view }; T.clear(); __ui.setView('pov', 'Daniel'); a.pov = T.$('view-pov').textContent + '/' + document.body.dataset.view + '/' + document.querySelector('[aria-pressed="true"]').dataset.view; document.querySelector('.view-chip[data-view="pov"]').click(); a.again = J(__calls);
    __ui.setView('nonsense'); a.junk = document.body.dataset.view; __ui.setView('pov', EVIL); a.evil = T.$('view-pov').textContent === 'Player: ' + EVIL && !document.querySelector('#views img'); __ui.setView('split'); const tall = innerWidth <= innerHeight, sb = T.box('split-line'); a.tall = tall; a.split = T.seen('split-line') + '/' + (tall ? sb.h : sb.w) + 'px/' + Math.round(tall ? sb.t + 1 - innerHeight / 2 : sb.l + 1 - innerWidth / 2) + '/' + Math.round(tall ? sb.w - innerWidth : sb.h - innerHeight) + '/' + T.$('view-pov').textContent; __ui.setView('free'); a.free = T.seen('split-line'); return a; }, EVIL);
  ok(r.calls === J([['view', 'pov'], ['view', 'split']]) && r.pressed === 'broadcast', `${tag} a chip click calls onView and marks nothing itself (${r.calls}, still ${r.pressed})`);
  ok(r.pov === 'Player: Daniel/pov/pov' && r.again === J([['view', 'pov']]) && r.junk === 'pov' && r.evil, `${tag} setView('pov', name): "${r.pov}"; the active Player chip calls again; an unknown view changes nothing`);
  ok(r.split === 'true/2px/0/0/Player' && r.free === false, `${tag} split: a 2 px line through the centre, ${r.tall ? 'ACROSS (a tall window stacks the two views)' : 'down the middle'}, and nothing else (${r.split}); gone in other views`);
  r = await ev(pg, async () => { __ui.toast('Matt · Club', 5000); await new Promise(r => setTimeout(r, 300)); const a = [getComputedStyle(T.$('views')).opacity]; __ui.toastOff(); await new Promise(r => setTimeout(r, 700)); a.push(getComputedStyle(T.$('views')).opacity); T.$('views').classList.add('is-idle'); await new Promise(r => setTimeout(r, 700)); a.push(getComputedStyle(T.$('views')).opacity); __ui.wake(); a.push(T.$('views').classList.contains('is-idle'), T.$('keys').classList.contains('is-idle')); return a; });
  ok(+r[0] < 0.2 && +r[1] === 1 && +r[2] === 0 && r[3] === false && r[4] === false, `${tag} chips yield to a toast, fade when idle and wake() brings them back (${J(r)})`);
  r = await ev(pg, () => { __ui.setWatchers(0); const a = [T.seen('watchers')]; __ui.setWatchers('junk'); a.push(T.seen('watchers')); __ui.setSpectator(false); a.push(document.body.dataset.role, document.body.dataset.view, T.seen('keys'), T.seen('views')); __ui.setWatchers(2); a.push(T.seen('watchers'), T.$('watchers').getAttribute('aria-label')); return a; });
  ok(J(r) === J([false, false, null, null, true, false, true, '2 watching']) || J(r) === J([false, false, undefined, undefined, true, false, true, '2 watching']), `${tag} setWatchers(0) hides the count; players see it too; setSpectator(false) restores the player HUD (${J(r)})`);
  await pg.close();

  // ---------- 3.5 banner, result, rematch, hold ----------
  pg = await mock(tag, 'hud', w, h);
  r = await ev(pg, (EVIL) => { const b = () => T.$('banner-text').textContent + ':' + (T.$('banner').classList.contains('is-me') ? 'blue' : 'orange'), a = []; for (const args of [[true], [true, 'Daniel'], [false], [false, 'Matt'], [null, 'Ann', 0], [null, 'Bo', 1], [null, '', 1], [false, EVIL]]) { __ui.pointBanner(...args); a.push(b()); } a.push(!document.querySelector('#banner img')); return a; }, EVIL);
  ok(J(r) === J(['Your point:blue', 'Your point:blue', 'Their point:orange', 'Matt scores:orange', 'Ann scores:blue', 'Bo scores:orange', 'Player 2 scores:orange', EVIL + ' scores:orange', true]), `${tag} pointBanner: ${r.slice(0, 7).join(' | ')}`);
  r = await ev(pg, async () => { __ui.hold('Daniel', 12); const a = { seen: T.seen('hold'), text: T.$('hold-text').textContent, left: T.$('hold-left').textContent, fit: T.inside('hold'), hits: ['board', 'corner', 'keys', 'banner-text'].filter(i => T.hit('hold', i)), veil: !!document.body.dataset.overlay, z: +getComputedStyle(T.$('hold')).zIndex > +getComputedStyle(T.$('board')).zIndex && +getComputedStyle(T.$('hold')).zIndex < +getComputedStyle(T.$('screen-lobby')).zIndex }; __ui.hold('Daniel', 11.4); a.left2 = T.$('hold-left').textContent; return a; });
  ok(r.seen && r.text === 'Waiting for Daniel' && r.left === '12' && r.left2 === '11' && r.fit && !r.hits.length && !r.veil && r.z, `${tag} hold card: "${r.text}" ${r.left}, over the HUD, under the menus, no veil, touches nothing (${r.hits})`);
  await pg.screenshot({ path: `${root}test/ui-shots/next-hold-${tag}.png` });
  r = await ev(pg, async () => { __ui.hold(null); await new Promise(r => setTimeout(r, 260)); const a = [T.seen('hold')];      // it shrinks away (200 ms, ui.css .hold-card) before it leaves the render tree
    __ui.hold('Bo', 9); __ui.matchResult({ won: true, me: 11, them: 9, nameThem: 'Bo' }); a.push(T.$('hold').hidden); __ui.showOverlay(null); __ui.hold('Bo', 3); __ui.showScreen('lobby'); a.push(getComputedStyle(T.$('hold')).display); __ui.showScreen(null); __ui.hold(null); return a; }); ok(J(r) === J([false, true, 'none']), `${tag} hold(null) and the result hide it; it never shows through the lobby glass (${J(r)})`);
  // result
  const res = () => ev(pg, () => ({ title: T.$('result-title').textContent, note: T.$('result-note').textContent, medal: T.$('medal').className.replace('medal ', ''), lose: T.$('result').classList.contains('is-lose'), names: T.$('tally-name-me').textContent + '/' + T.$('tally-name-them').textContent, sc: T.$('tally-sc-me').textContent + '-' + T.$('tally-sc-them').textContent, win: T.$('tally-me').classList.contains('is-winner') ? 'L' : T.$('tally-them').classList.contains('is-winner') ? 'R' : '',
    btns: T.seen('btn-rematch') && T.seen('btn-leave') ? T.$('btn-rematch').textContent + '/' + T.$('btn-leave').textContent : '', rnote: T.$('rematch-note').textContent, count: T.seen('rematch-count') ? T.$('rematch-left').textContent : null, overlay: __ui.currentOverlay(), focus: document.activeElement.id, fit: T.inside('result'), btnCls: T.$('btn-rematch').className }));
  await ev(pg, () => { T.clear(); __ui.matchResult({ won: true, me: 11, them: 8, nameThem: 'Matt' }); __ui.rematch({ mine: null, theirs: null, left: 20, name: 'Matt' }); }); await sleep(900); r = await res();
  ok(r.title === 'You win!' && r.medal === 'is-gold' && !r.lose && r.names === 'You/Matt' && r.sc === '11-8' && r.win === 'L' && r.note === '' && r.overlay === 'match', `${tag} result, player won: "${r.title}" ${r.medal} ${r.names} ${r.sc}`);
  ok(r.btns === 'Rematch/Leave' && r.rnote === '' && /^(20|19)$/.test(r.count) && r.focus === 'btn-rematch' && r.fit && /\bbtn\b/.test(r.btnCls), `${tag} Rematch / Leave, countdown ${r.count}, focus on Rematch (${r.focus}), card fits`);
  await pg.screenshot({ path: `${root}test/ui-shots/next-result-${tag}.png` });
  await ev(pg, () => __ui.rematch({ theirs: true })); r = await res(); ok(r.rnote === 'Matt wants a rematch', `${tag} rematch note, they said yes: "${r.rnote}"`);
  await pg.keyboard.press('Enter'); await sleep(60); r = await ev(pg, () => ({ calls: J(__calls), dis: T.$('btn-rematch').disabled && !T.$('btn-leave').disabled, pressed: T.$('btn-rematch').classList.contains('is-pressed') && !T.$('btn-leave').classList.contains('is-pressed'), op: [getComputedStyle(T.$('btn-rematch')).opacity, getComputedStyle(T.$('btn-leave')).opacity] })); T: 0;
  ok(r.calls === J([['vote', true]]) && r.dis && r.pressed && +r.op[0] === 1 && +r.op[1] === 1, `${tag} Enter on Rematch -> onRematch(true); Rematch locks and stays lit, Leave stays open (${r.calls}, opacity ${r.op})`);
  await ev(pg, () => { T.$('btn-rematch').click(); }); ok(await ev(pg, () => __calls.length) === 1, `${tag} a second Rematch votes nothing`);
  await ev(pg, () => { T.$('btn-leave').click(); T.$('btn-leave').click(); T.$('btn-rematch').click(); }); ok(await ev(pg, () => J(__calls)) === J([['vote', true], ['vote', false]]) && await ev(pg, () => T.$('btn-leave').disabled && T.$('btn-rematch').disabled), `${tag} Leave after Rematch is a change of mind: onRematch(false), once, then both lock`);
  r = await ev(pg, () => { const n = () => T.$('rematch-note').textContent, a = []; __ui.rematch({ mine: true, theirs: null }); a.push(n()); __ui.rematch({ theirs: false }); a.push(n()); __ui.rematch({ mine: null, theirs: null }); a.push(n()); __ui.rematch({ name: 'Bo', theirs: true }); a.push(n()); __ui.rematch(); __ui.rematch({}); a.push(n()); return a; });
  ok(J(r) === J(['Waiting for Matt', 'Matt left', '', 'Bo wants a rematch', 'Bo wants a rematch']), `${tag} rematch notes: ${r.join(' | ')}`);
  r = await ev(pg, async () => { __ui.rematch({ left: 5 }); const a = [T.$('rematch-left').textContent]; await new Promise(r => setTimeout(r, 2200)); a.push(T.$('rematch-left').textContent, getComputedStyle(T.$('rematch-bar')).getPropertyValue('--p')); __ui.showOverlay(null); await new Promise(r => setTimeout(r, 1300)); a.push(T.$('rematch-left').textContent); return a; });
  ok(r[0] === '5' && r[1] === '3' && Math.abs(+r[2] - 3 / 20) < 0.01 && r[3] === r[1], `${tag} the seconds tick here (5 -> ${r[1]} in 2.2 s), the bar drains from the first number (${r[2]} of the bar), showOverlay(null) stops it (${r[3]})`);
  await ev(pg, () => { T.clear(); __ui.matchResult({ won: false, me: 9, them: 11, nameThem: 'Bo', forfeit: false }); __ui.rematch({ left: 20, name: 'Bo' }); }); await sleep(200); r = await res(); const b2 = await ev(pg, () => !T.$('btn-rematch').disabled && !T.$('btn-rematch').classList.contains('is-pressed'));
  ok(r.title === 'Bo wins' && r.medal === 'is-silver' && r.lose && r.win === 'R' && r.btns && b2, `${tag} result, player lost: "${r.title}" ${r.medal}; a new result re-arms the buttons`);
  await pg.click('#btn-leave'); r = await ev(pg, () => J(__calls) + T.$('btn-leave').classList.contains('is-pressed')); ok(r === J([['vote', false]]) + 'true', `${tag} Leave -> onRematch(false) (${r})`);
  await ev(pg, () => __ui.matchResult({ won: true, me: 6, them: 4, nameThem: 'Bo', forfeit: true })); r = await res(); ok(r.note === 'Bo left' && r.title === 'You win!', `${tag} forfeit note: "${r.note}"`);
  await ev(pg, () => { __ui.setSpectator(true); __ui.matchResult({ won: false, me: 9, them: 11, nameMe: 'Ann', nameThem: 'Bo', role: 'spectator', forfeit: true }); __ui.rematch({ left: 16 }); __ui.rematch({ mine: true, theirs: true, name: 'x' }); }); await sleep(200); r = await res();
  ok(r.title === 'Bo wins' && r.medal === 'is-gold' && !r.lose && r.names === 'Ann/Bo' && r.btns === '' && r.rnote === '' && r.count === null && r.note === 'Ann left' && r.win === 'R', `${tag} spectator result after a forfeit: "${r.title}", gold, no buttons, no rematch to wait for ("${r.rnote}"), no clock (${r.count}), "${r.note}"`);
  await pg.screenshot({ path: `${root}test/ui-shots/next-result-watch-${tag}.png` });
  await ev(pg, () => { __ui.setSpectator(false); __ui.matchResult(true, 11, 8, 'Club Bot'); }); await sleep(100); r = await res(); ok(r.title === 'You win!' && r.names === 'You/Club Bot' && r.sc === '11-8' && r.btns === '' && r.rnote === 'Rematch starting' && r.count === null, `${tag} the old positional matchResult still works: no vote, "${r.rnote}"`);
  await ev(pg, () => __ui.matchResult(false, 3, 11, 'Pro Bot')); r = await res(); ok(r.title === 'Pro Bot wins' && r.lose, `${tag} old positional loss: "${r.title}"`);
  // hostile name, everywhere a name goes
  r = await ev(pg, (EVIL) => { __ui.showOverlay(null); __ui.setNames({ me: EVIL, them: EVIL, meSub: EVIL, themSub: EVIL }); __ui.pointBanner(false, EVIL); __ui.pointBanner(null, EVIL, 0); __ui.joinBanner(EVIL); __ui.joinBanner(EVIL, false); __ui.hold(EVIL, 3); __ui.setView('pov', EVIL); __ui.toast(EVIL + ' joined'); __ui.matchResult({ won: false, me: 1, them: 11, nameMe: EVIL, nameThem: EVIL, forfeit: true, role: 'spectator' }); __ui.matchResult({ won: false, me: 1, them: 11, nameThem: EVIL, forfeit: true }); __ui.rematch({ theirs: true, name: EVIL });
    const a = { note: T.$('rematch-note').textContent, title: T.$('result-title').textContent, hold: T.$('hold-text').textContent }; __ui.rematch({ theirs: false }); __ui.rematch({ mine: true, theirs: null }); const i = T.$('name-input'); i.value = EVIL; i.dispatchEvent(new Event('input', { bubbles: true })); a.name = __ui.playerName();
    a.imgs = document.querySelectorAll('#ui-root img').length; a.xss = window.__xss; return a; }, EVIL); await sleep(300);
  ok(r.imgs === 0 && r.xss === undefined && await ev(pg, () => window.__xss) === undefined && r.title === EVIL + ' wins' && r.note === EVIL + ' wants a rematch' && r.hold === 'Waiting for ' + EVIL && !/[<>]/.test(r.name), `${tag} a hostile name is text everywhere (title "${r.title.slice(0, 18)}", 0 <img>, no script ran; my own name is cleaned to "${r.name}")`);
  await pg.close();
}

// ---------- Part B: the real page, whatever main.js is on disk ----------
if (ONLY.includes('b')) {
  const got = [], COURT = { halfW: 3.05, halfL: 6.7, kitchen: 2.13, net: 0.91 }, LIST = { type: 'lobby', online: 3, rooms: [{ code: 'KXQ7', players: 1, open: true, watch: 8, watchers: 0, score: [0, 0], live: false }, { code: 'M3PD', players: 2, open: false, watch: 6, watchers: 2, score: [7, 4], live: true }] };
  const wss = new WebSocketServer({ port: G, host: '127.0.0.1' }); wss.on('connection', ws => { ws.send(J(LIST)); ws.on('message', raw => { const m = JSON.parse(raw); if (m.type === 'ping') return ws.send(J({ type: 'pong', c: m.c })); got.push(m);
    if (m.type === 'quick') { ws.send(J({ type: 'room', code: 'QQQQ', public: true, role: 'player' })); ws.send(J({ type: 'welcome', side: 0, role: 'player', court: COURT, names: [m.name || 'Player 1', null] })); } }); });
  const before = errs.length, pg = await browser.newPage(); await pg.setViewport({ width: 1280, height: 720 }); watchPage(pg, 'real');
  await pg.goto(`http://127.0.0.1:${W}/web/index.html?uitest=1&cam=0&game=${G}&bridge=${DEAD}`); await sleep(2200);
  let r = await ev(pg, () => ({ screen: document.body.dataset.screen, ui: typeof window.__ui, canvas: !!document.querySelector('#stage canvas') }));
  ok(r.screen === 'title' && r.canvas, `real page boots with the main.js on disk: screen ${r.screen}, canvas ${r.canvas}, __ui ${r.ui}`);
  await ev(pg, () => { try { localStorage.removeItem('poddle.name'); } catch {} }); await pg.reload(); await sleep(2200);
  await pg.click('#btn-start'); await sleep(900); r = await ev(pg, () => ({ screen: document.body.dataset.screen, focus: document.activeElement.id, rooms: [...document.querySelectorAll('#room-list > li')].map(l => l.textContent).join('|'), sub: document.getElementById('courts-n').textContent, online: document.getElementById('lobby-online').textContent }));
  ok(r.screen === 'lobby' && r.focus === 'name-input' && r.rooms === 'KXQ7A player is waitingJoinWatch' && r.sub === '1 open', `real page: Play -> lobby, first visit asks for the name (${r.focus}); list: ${r.rooms}`);
  await pg.click('#btn-quick'); await sleep(300); ok(!got.length, `real page: Quick play with no name sends nothing (${J(got)})`);
  await pg.keyboard.type('Daniel'); await pg.keyboard.press('Enter'); await sleep(100); await pg.keyboard.press('Enter'); await sleep(1200); r = await ev(pg, () => ({ screen: document.body.dataset.screen, pill: document.getElementById('room-code').textContent }));
  ok(got.length === 1 && got[0].type === 'quick' && (got[0].name === undefined || got[0].name === 'Daniel') && r.screen === 'connect' && r.pill === 'QQQQ', `real page: name, Enter, Enter -> ${J(got[0])} -> ${r.screen}, room ${r.pill}`);
  await pg.screenshot({ path: `${root}test/ui-shots/next-real-connect-1280x720.png` });
  const mine = errs.slice(before); ok(!mine.length, 'real page: no page errors' + (mine.length ? ':\n  ' + [...new Set(mine.map(e => e.split('\n')[0].slice(0, 220)))].join('\n  ') : ''));
  await pg.close(); for (const c of wss.clients) c.terminate(); await new Promise(r => wss.close(r));
}

const uniq = [...new Set(errs.map(e => e.split('\n')[0].slice(0, 220)))];
ok(!uniq.length, 'no console errors' + (uniq.length ? ':\n  ' + uniq.join('\n  ') : ''));
console.log(out.join('\n')); const bad = out.filter(l => l.startsWith('FAIL')).length;
console.log(`${out.length - bad} passed, ${bad} failed`); console.log(bad ? 'UI-NEXT FAIL' : 'UI-NEXT PASS');
await browser.close(); web.close(); process.exit(bad ? 1 : 0);
